"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - idea_maker(state: GraphState, config: RunnableConfig) (line 17)
        - idea_hater(state: GraphState, config: RunnableConfig) (line 52)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from langchain_core.runnables import RunnableConfig

from ..paper_agents.tools import extract_latex_block, LLM_call_stream, clean_section
from .prompts import idea_maker_prompt, idea_hater_prompt
from .parameters import GraphState
from ..paper_agents.literature import _execute_query

def perform_deep_research(query: str, keys) -> str:
    """
    Perform deep research on a topic using Perplexity.
    """
    if not keys.PERPLEXITY:
        return "No Perplexity API key available for deep research."
        
    print(f"Performing deep research on: {query[:50]}...")
    
    payload = {
        "model": "sonar-reasoning-pro",
        "messages": [
            {
                "role": "system",
                "content": "You are a senior scientific researcher. Provide a comprehensive summary of the state-of-the-art relevant to the query. Focus on recent advancements, open problems, and key papers. Be dense and technical."
            },
            {
                "role": "user",
                "content": query
            }
        ],
        "temperature": 0.1
    }
    
    try:
        response = _execute_query(payload, keys)
        return response["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"Deep research failed: {e}")
        return "Deep research unavailable due to error."

def idea_maker(state: GraphState, config: RunnableConfig):

    print(f"Maker (iteration {state['idea']['iteration']+1})")
    
    # Perform Deep Research in the first iteration or if context is missing
    if state['idea']['iteration'] == 0 or 'research_context' not in state['idea']:
        # Extract a search query from the data description (naive approach: use first 200 chars)
        # Ideally, we would ask an LLM to generate a query, but for now we use the description summary
        search_query = f"State of the art research for: {state['data_description'][:300]}"
        research_context = perform_deep_research(search_query, state['keys'])
        state['idea']['research_context'] = research_context
    
    PROMPT = idea_maker_prompt(state)
    state, result = LLM_call_stream(PROMPT, state)
    text = extract_latex_block(state, result, "IDEA")

    # remove LLM added lines
    text = clean_section(text, "IDEA")

    #with open(state['files']['idea_log'], 'a') as f:
    #    f.write(f"""Iteration {state['idea']['iteration']}:
#{text}
#---------------------------------------------
#""")

    state['idea']['idea'] = text
    state['idea']['previous_ideas'] = f"""
{state['idea']['previous_ideas']}

Iteration {state['idea']['iteration']}:
Idea: {text}
"""
    state['idea']['iteration'] += 1

    if state['idea']['iteration']==state['idea']['total_iterations']:
        with open(state['files']['idea'], 'w') as f:
            f.write(text)

        print(f"done {state['tokens']['ti']} {state['tokens']['to']}")
    
    return {"idea": state['idea']}


def idea_hater(state: GraphState, config: RunnableConfig):

    #print('Hater...', end="", flush=True)
    print(f"Hater (iteration {state['idea']['iteration']})")
    
    PROMPT = idea_hater_prompt(state)
    state, result = LLM_call_stream(PROMPT, state)
    text = extract_latex_block(state, result, "CRITIC")

    # remove LLM added lines
    text = clean_section(text, "CRITIC")
    
    state['idea']['criticism'] = text

    #with open(state['files']['idea_log'], 'a') as f:
    #    f.write(f"""Criticism:
#{text}
#---------------------------------------------
#""")

    return {"idea": state['idea']}


