"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5

    Classes/Functions:
        - methods_fast(state: GraphState, config: RunnableConfig) (line 16)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from langchain_core.runnables import RunnableConfig
from langchain_core.messages import HumanMessage

from ..paper_agents.tools import extract_latex_block, LLM_call_stream, clean_section
from ..tools import create_wolfram_tool
from .prompts import methods_fast_prompt
from .parameters import GraphState


def methods_fast(state: GraphState, config: RunnableConfig):

    print('Generating methods...', end="", flush=True)

    # Initialize Wolfram Alpha tool
    wolfram_tool = create_wolfram_tool(enable_hitl=False)

    # Get the LLM instance for tool usage
    llm = state['llm']['llm']

    # Bind the tool to the LLM
    llm_with_tools = llm.bind_tools([wolfram_tool])

    PROMPT = methods_fast_prompt(state)

    # Use the tool-enabled LLM
    state, result = LLM_call_stream_with_tools(PROMPT, state, llm_with_tools)
    text = extract_latex_block(state, result, "METHODS")

    # remove LLM added lines
    text = clean_section(text, "METHODS")

    with open(state['files']['methods'], 'w') as f:
        f.write(text)

    print(f"done {state['tokens']['ti']} {state['tokens']['to']}")


def LLM_call_stream_with_tools(prompt, state, llm_with_tools):
    """
    Calls the LLM with streaming enabled and tool support.
    Also updates token usage tracking.
    """
    output_file_path = state['files']['f_stream']

    # Start streaming and writing/printing immediately
    full_content = ''
    state['tokens']['i'] = 0
    state['tokens']['o'] = 0
    with open(output_file_path, 'a') as f:
        for chunk in llm_with_tools.stream(prompt):
            text = chunk.content
            f.write(text)
            f.flush()  # Immediate file write
            if state['llm']['stream_verbose']:
                print(text, end='', flush=True)  # Immediate terminal output
            full_content += text

            # After streaming, get token usage
            usage = chunk.usage_metadata if hasattr(
                chunk, 'usage_metadata') else None
            if usage:
                input_tokens = usage.get('input_tokens', 0)
                output_tokens = usage.get('output_tokens', 0)
                if output_tokens > state['llm']['max_output_tokens']:
                    print('WARNING!! Max output tokens reached!')

                state['tokens']['ti'] += input_tokens
                state['tokens']['to'] += output_tokens
                state['tokens']['i'] += input_tokens
                state['tokens']['o'] += output_tokens
        f.write('\n\n')
    with open(state['files']['LLM_calls'], 'a') as f:
        f.write(
            f"{
                state['tokens']['i']} {
                state['tokens']['o']} {
                state['tokens']['ti']} {
                    state['tokens']['to']}\n")

    return state, full_content
