"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5

    Classes/Functions:
        - pdf_to_images(pdf_path: str, out_dir: str = None, dpi: int = 200, fmt: str = 'png', password: str = None, transparent: bool = False, keep_images=False) (line 14)
    --- END AUTO-GENERATED DOCSTRING ---
"""
import os
import fitz  # PyMuPDF
import base64


def pdf_to_images(
        pdf_path: str,
        out_dir: str = None,
        dpi: int = 200,
        fmt: str = "png",
        password: str = None,
        transparent: bool = False,
        keep_images=False):
    """
    Convert all pages of a PDF to images.

    Args:
        pdf_path: Path to the input PDF.
        out_dir: Output directory (created if missing). Defaults to <pdf_stem>_pages next to the PDF.
        dpi: Resolution (dots per inch). 200–300 is good for papers.
        fmt: Image format: 'png' or 'jpg' (others supported too).
        password: PDF password if encrypted.
        transparent: If True, keeps alpha channel (PNG only).
    """

    raise RuntimeError(
        'PDF to image conversion is disabled. Provide raster images or enable PyMuPDF support.')
