"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5

    Classes/Functions:
        - pdf_to_images(pdf_path: str, out_dir: str = None, dpi: int = 200, fmt: str = 'png', password: str = None, transparent: bool = False, keep_images=False) (line 14)
    --- END AUTO-GENERATED DOCSTRING ---
"""
import os
import fitz  # PyMuPDF
import base64


def pdf_to_images(
        pdf_path: str,
        out_dir: str = None,
        dpi: int = 200,
        fmt: str = "png",
        password: str = None,
        transparent: bool = False,
        keep_images=False):
    """
    Convert all pages of a PDF to images.

    Args:
        pdf_path: Path to the input PDF.
        out_dir: Output directory (created if missing). Defaults to <pdf_stem>_pages next to the PDF.
        dpi: Resolution (dots per inch). 200–300 is good for papers.
        fmt: Image format: 'png' or 'jpg' (others supported too).
        password: PDF password if encrypted.
        transparent: If True, keeps alpha channel (PNG only).
    """
    
    if not os.path.exists(pdf_path):
        raise FileNotFoundError(f"PDF file not found: {pdf_path}")

    # Use the input filename (without extension) for the default output directory
    if out_dir is None:
        pdf_stem = os.path.splitext(os.path.basename(pdf_path))[0]
        out_dir = os.path.join(os.path.dirname(pdf_path), f"{pdf_stem}_pages")

    os.makedirs(out_dir, exist_ok=True)

    try:
        doc = fitz.open(pdf_path)
        if password:
            doc.authenticate(password)
    except Exception as e:
        raise ValueError(f"Could not open PDF '{pdf_path}': {e}")

    image_paths = []

    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        
        # Calculate matrix for desired DPI (72 is the default PDF DPI)
        zoom = dpi / 72
        mat = fitz.Matrix(zoom, zoom)
        
        pix = page.get_pixmap(matrix=mat, alpha=transparent)
        
        output_filename = f"page_{page_num + 1:03d}.{fmt}"
        output_path = os.path.join(out_dir, output_filename)
        
        pix.save(output_path)
        image_paths.append(output_path)

    doc.close()
    
    if not keep_images:
        # If the user doesn't want to keep images, we might return base64 strings or similar
        # But this function signature implies file generation. 
        # For now, we return paths. If 'keep_images' is False, the caller handles cleanup 
        # or we could implement a temp dir approach.
        pass

    return image_paths
