"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - task_router(state: GraphState) -> str (line 15)
        - router(state: GraphState) -> str (line 29)
        - literature_router(state: GraphState) -> str (line 36)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from .parameters import GraphState


# idea - methods router
def task_router (state: GraphState) -> str:

    if state['task']=='idea_generation':
        return 'maker'
    elif state['task']=='methods_generation':
        return 'methods'
    elif state['task']=='literature':
        return 'novelty'
    elif state['task']=='referee':
        return 'referee'
    else:
        raise Exception('Wrong task choosen!')
    
# Idea maker - hater router
def router(state: GraphState) -> str:

    if state['idea']['iteration']<state['idea']['total_iterations']:
        return "hater"
    else: 
        return "__end__"

def literature_router(state: GraphState) -> str:
    """
    This simple function determines which agent should go after calling the novelty_decider one
    """

    return state['literature']['next_agent']
