"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - citation_router(state: GraphState) -> str (line 13)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from .parameters import GraphState


# idea - methods router
def citation_router (state: GraphState) -> str:

    if   state['paper']['add_citations'] is True:
        return 'citations_node'
    elif state['paper']['add_citations'] is False:
        return '__end__'
    else:
        raise Exception('Wrong add_citations value')
