"""
--- AUTO-GENERATED DOCSTRING ---
Table of content is automatically generated by Agent Docstrings v1.3.5

Classes/Functions:
    - KeyManager (line 16):
        - get_keys_from_env() -> None (line 23)
        - __getitem__(key: str) -> str (line 33)
        - __setitem__(key: str, value: str) -> None (line 36)
--- END AUTO-GENERATED DOCSTRING ---
"""
import os
from pydantic import BaseModel
from dotenv import load_dotenv


class KeyManager(BaseModel):
<<<<<<< HEAD
    ANTHROPIC: str | None = ""
    GEMINI: str | None = ""
    OPENAI: str | None = ""
    PERPLEXITY: str | None = ""
    SEMANTIC_SCHOLAR: str | None = ""
=======
    ANTHROPIC: str = ""
    GEMINI: str = ""
    OPENAI: str = ""
    PERPLEXITY: str = ""
    SEMANTIC_SCHOLAR: str = ""
    WOLFRAM_APP_ID: str = ""
>>>>>>> 88373a30590704ac30cc9794e11c9da2ffcfc402

    def get_keys_from_env(self) -> None:
        load_dotenv()
        self.OPENAI = os.getenv("OPENAI_API_KEY")
        self.GEMINI = os.getenv("GOOGLE_API_KEY")
        # not strictly needed
        self.ANTHROPIC = os.getenv("ANTHROPIC_API_KEY")
        # only for citations
        self.PERPLEXITY = os.getenv("PERPLEXITY_API_KEY")
        # only for fast semantic scholar
        self.SEMANTIC_SCHOLAR = os.getenv("SEMANTIC_SCHOLAR_KEY")
        self.WOLFRAM_APP_ID = os.getenv("WOLFRAM_APP_ID")

    def __getitem__(self, key: str) -> str:
        return getattr(self, key)

    def __setitem__(self, key: str, value: str) -> None:
        setattr(self, key, value)
