"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5
    
    Classes/Functions:
        - LLM (line 12):
    --- END AUTO-GENERATED DOCSTRING ---
"""
from pydantic import BaseModel
from typing import Dict

class LLM(BaseModel):
    """LLM base model"""
    name: str
    """Name/identifier of the model."""
    max_output_tokens: int
    """Maximum output tokens allowed."""
    temperature: float | None
    """Temperature of the model."""

gemini3flash = LLM(name="gemini-3-flash",
                   max_output_tokens=65536,
                   temperature=0.7)
"""`gemini-3-flash` model."""

gemini3propreview = LLM(name="gemini-3-pro-preview",
                        max_output_tokens=65536,
                        temperature=0.7)
"""`gemini-3-pro-preview` model."""

models : Dict[str, LLM] = {
                            "gemini-3-flash" : gemini3flash,
                            "gemini-3-pro-preview" : gemini3propreview,
                           }
"""Dictionary with the available models (Restricted to Gemini-3)."""
