<<<<<<< HEAD
import os
import re
from pathlib import Path
import warnings

from .llm import LLM, models
=======
"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5

    Classes/Functions:
        - input_check(str_input: str) -> str (line 13)
        - llm_parser(llm: LLM | str) -> LLM (line 25)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from .llm import LLM, models
from .key_manager import KeyManager  # noqa: F401
import os
from typing import Dict

>>>>>>> 88373a30590704ac30cc9794e11c9da2ffcfc402

def input_check(str_input: str) -> str:
    """Check if input is a string or a markdown file path and return content.

    If a file path ending with ".md" is provided, read and return its content.
    Otherwise, return the string as-is.
    """

    if str_input.endswith(".md"):
        with open(str_input, 'r') as f:
            content = f.read()
    elif isinstance(str_input, str):
        content = str_input
    else:
        raise ValueError(
            "Input must be a string or a path to a markdown file.")
    return content


def llm_parser(llm: LLM | str) -> LLM:
    """Get the LLM instance from a string."""

    if isinstance(llm, str):
        try:
            llm = models[llm]
        except KeyError:
            keys = list(models.keys())
            raise KeyError(
                f"LLM '{llm}' not available. Please select from: {keys}")
    return llm

<<<<<<< HEAD
def extract_file_paths(markdown_text):
    """
    Extract the bulleted file paths from markdown text 
    and check if they exist and are absolute paths.
    
    Args:
        markdown_text (str): The markdown text containing file paths
    
    Returns:
        tuple: (existing_paths, missing_paths)
    """
    
    # Pattern to match file paths in markdown bullet points
    pattern = r'-\s*([^\n]+\.(?:csv|txt|md|py|json|yaml|yml|xml|html|css|js|ts|tsx|jsx|java|cpp|c|h|hpp|go|rs|php|rb|pl|sh|bat|sql|log))'
    
    # Find all matches
    matches = re.findall(pattern, markdown_text, re.IGNORECASE)
    
    # Clean up paths and check existence
    existing_paths = []
    missing_paths = []
    
    for match in matches:
        path = match.strip()
        if os.path.exists(path) and os.path.isabs(path):
            existing_paths.append(path)
        else:
            missing_paths.append(path)
    
    return existing_paths, missing_paths

def check_file_paths(content: str) -> None:
    """Check that file paths indicated in content text have the proper format"""

    existing_paths, missing_paths = extract_file_paths(content)

    if len(missing_paths) > 0:
        warnings.warn(
            f"The following data files paths in the data description are not in the right format or do not exist:\n"
            f"{missing_paths}\n"
            f"Please fix them according to the convention '- /absolute/path/to/file.ext'\n"
            f"otherwise this may cause hallucinations in the LLMs."
        )

    if len(existing_paths) == 0:
        warnings.warn(
            "No data files paths were found in the data description. If you want to provide input data, ensure that you indicate their path, otherwise this may cause hallucinations in the LLM in the get_results() workflow later on."
        )

def create_work_dir(work_dir: str | Path, name: str) -> Path:
    """Create working directory"""

    work_dir = os.path.join(work_dir, f"{name}_generation_output")
    os.makedirs(work_dir, exist_ok=True)
    return Path(work_dir)

def get_task_result(chat_history, name: str):
    """Get task result from chat history"""
    
    for obj in chat_history[::-1]:
        if obj['name'] == name:
            result = obj['content']
            break
    task_result = result
    return task_result

def in_notebook():
    """Check whether the code is run from a Jupyter Notebook or not, to use different display options"""
    
    try:
        from IPython import get_ipython # type: ignore
        if 'IPKernelApp' not in get_ipython().config:  # type: ignore # pragma: no cover
            return False
    except ImportError:
        return False
    except AttributeError:
        return False
    return True
=======

# * Wolfram Alpha adapter with caching, structured parsing, and HITL
class WolframAlphaClient:
    """Enhanced client for Wolfram|Alpha Full Results API with caching and structured parsing.

    Features:
    - File-based caching with checksums
    - Structured result parsing (LaTeX, MathML, images)
    - HITL support for ambiguous responses
    - Error handling and retry logic
    """

    def __init__(self, app_id: str | None = None, timeout_s: int = 20,
                 cache_dir: str | None = None, enable_hitl: bool = False):
        import requests
        import hashlib
        import json
        from pathlib import Path

        self._requests = requests
        self._hashlib = hashlib
        self._json = json
        self._Path = Path

        self.app_id = app_id or os.getenv("WOLFRAM_APP_ID")
        self.timeout_s = timeout_s
        self.enable_hitl = enable_hitl

        if not self.app_id:
            raise RuntimeError("WOLFRAM_APP_ID not configured")

        # Setup cache directory
        self.cache_dir = Path(
            cache_dir or os.path.join(
                os.getcwd(), ".wolfram_cache"))
        self.cache_dir.mkdir(exist_ok=True)

    def _get_cache_key(self, query: str) -> str:
        """Generate cache key from normalized query."""
        normalized = query.strip().lower()
        return self._hashlib.md5(normalized.encode()).hexdigest()

    def _load_from_cache(self, cache_key: str) -> Dict | None:
        """Load result from cache if available."""
        cache_file = self.cache_dir / f"{cache_key}.json"
        if cache_file.exists():
            try:
                with open(cache_file, 'r') as f:
                    return self._json.load(f)
            except Exception:
                return None
        return None

    def _save_to_cache(self, cache_key: str, result: Dict) -> None:
        """Save result to cache."""
        cache_file = self.cache_dir / f"{cache_key}.json"
        try:
            with open(cache_file, 'w') as f:
                self._json.dump(result, f, indent=2)
        except Exception:
            pass  # Cache failures shouldn't break the main flow

    def query(self, q: str, use_cache: bool = True) -> Dict:
        """Query Wolfram Alpha with optional caching."""
        cache_key = self._get_cache_key(q)

        # Try cache first
        if use_cache:
            cached = self._load_from_cache(cache_key)
            if cached:
                return cached

        # Make API call
        url = "https://api.wolframalpha.com/v2/query"
        params = {
            "input": q,
            "appid": self.app_id,
            "output": "JSON",
            "format": "plaintext,mathml,image",
        }

        try:
            resp = self._requests.get(
                url, params=params, timeout=self.timeout_s)
            resp.raise_for_status()
            result = resp.json()

            # Cache successful results
            if result.get("queryresult", {}).get("success"):
                self._save_to_cache(cache_key, result)

            return result
        except Exception as e:
            raise RuntimeError(f"Wolfram Alpha query failed: {e}")

    @staticmethod
    def extract_primary_text(wa_json: Dict) -> str | None:
        """Extract primary plaintext result."""
        try:
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                if pod.get("primary"):
                    subs = pod.get("subpods", [])
                    for sp in subs:
                        pt = sp.get("plaintext")
                        if pt:
                            return pt
            for pod in pods:
                for sp in pod.get("subpods", []):
                    pt = sp.get("plaintext")
                    if pt:
                        return pt
        except Exception:
            return None
        return None

    @staticmethod
    def extract_structured_results(wa_json: Dict) -> Dict:
        """Extract structured results including LaTeX, MathML, and images."""
        result = {
            "plaintext": [],
            "latex": [],
            "mathml": [],
            "images": [],
            "assumptions": [],
            "sources": []
        }

        try:
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                # Extract assumptions
                if "assumptions" in pod:
                    result["assumptions"].extend(pod["assumptions"])

                # Extract sources
                if "sources" in pod:
                    result["sources"].extend(pod["sources"])

                # Extract subpod content
                for subpod in pod.get("subpods", []):
                    if "plaintext" in subpod:
                        result["plaintext"].append(subpod["plaintext"])
                    if "mathml" in subpod:
                        result["mathml"].append(subpod["mathml"])
                    if "latex" in subpod:
                        result["latex"].append(subpod["latex"])
                    if "img" in subpod:
                        result["images"].append(subpod["img"])

        except Exception:
            pass

        return result

    def needs_hitl_review(self, wa_json: Dict) -> bool:
        """Check if result needs human review (ambiguous, multiple interpretations)."""
        if not self.enable_hitl:
            return False

        try:
            # Check for ambiguous results
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                # Multiple interpretations
                if len(pod.get("subpods", [])) > 3:
                    return True
                # Assumptions that might need review
                if pod.get("assumptions"):
                    return True
                # Error or warning states
                if pod.get("error") or pod.get("warning"):
                    return True
        except Exception:
            pass

        return False

    def get_hitl_prompt(self, query: str, wa_json: Dict) -> str:
        """Generate HITL review prompt for ambiguous results."""
        structured = self.extract_structured_results(wa_json)

        prompt = f"""Wolfram Alpha returned ambiguous results for query: "{query}"

Results:
- Plaintext: {structured['plaintext'][:3]}
- Assumptions: {structured['assumptions'][:2]}
- Sources: {structured['sources'][:2]}

Please review and select the most appropriate result, or provide clarification."""

        return prompt
>>>>>>> 88373a30590704ac30cc9794e11c9da2ffcfc402
