"""
    --- AUTO-GENERATED DOCSTRING ---
    Table of content is automatically generated by Agent Docstrings v1.3.5

    Classes/Functions:
        - input_check(str_input: str) -> str (line 13)
        - llm_parser(llm: LLM | str) -> LLM (line 25)
    --- END AUTO-GENERATED DOCSTRING ---
"""
from .llm import LLM, models
from .key_manager import KeyManager  # noqa: F401
import os
from typing import Dict


def input_check(str_input: str) -> str:
    """Check if input is a string or a markdown file path and return content.

    If a file path ending with ".md" is provided, read and return its content.
    Otherwise, return the string as-is.
    """

    if str_input.endswith(".md"):
        with open(str_input, 'r') as f:
            content = f.read()
    elif isinstance(str_input, str):
        content = str_input
    else:
        raise ValueError(
            "Input must be a string or a path to a markdown file.")
    return content


def llm_parser(llm: LLM | str) -> LLM:
    """Get the LLM instance from a string."""
    if isinstance(llm, str):
        try:
            llm = models[llm]
        except KeyError:
            keys = list(models.keys())
            raise KeyError(
                f"LLM '{llm}' not available. Please select from: {keys}")
    return llm


# * Wolfram Alpha adapter with caching, structured parsing, and HITL
class WolframAlphaClient:
    """Enhanced client for Wolfram|Alpha Full Results API with caching and structured parsing.

    Features:
    - File-based caching with checksums
    - Structured result parsing (LaTeX, MathML, images)
    - HITL support for ambiguous responses
    - Error handling and retry logic
    """

    def __init__(self, app_id: str | None = None, timeout_s: int = 20,
                 cache_dir: str | None = None, enable_hitl: bool = False):
        import requests
        import hashlib
        import json
        from pathlib import Path

        self._requests = requests
        self._hashlib = hashlib
        self._json = json
        self._Path = Path

        self.app_id = app_id or os.getenv("WOLFRAM_APP_ID")
        self.timeout_s = timeout_s
        self.enable_hitl = enable_hitl

        if not self.app_id:
            raise RuntimeError("WOLFRAM_APP_ID not configured")

        # Setup cache directory
        self.cache_dir = Path(
            cache_dir or os.path.join(
                os.getcwd(), ".wolfram_cache"))
        self.cache_dir.mkdir(exist_ok=True)

    def _get_cache_key(self, query: str) -> str:
        """Generate cache key from normalized query."""
        normalized = query.strip().lower()
        return self._hashlib.md5(normalized.encode()).hexdigest()

    def _load_from_cache(self, cache_key: str) -> Dict | None:
        """Load result from cache if available."""
        cache_file = self.cache_dir / f"{cache_key}.json"
        if cache_file.exists():
            try:
                with open(cache_file, 'r') as f:
                    return self._json.load(f)
            except Exception:
                return None
        return None

    def _save_to_cache(self, cache_key: str, result: Dict) -> None:
        """Save result to cache."""
        cache_file = self.cache_dir / f"{cache_key}.json"
        try:
            with open(cache_file, 'w') as f:
                self._json.dump(result, f, indent=2)
        except Exception:
            pass  # Cache failures shouldn't break the main flow

    def query(self, q: str, use_cache: bool = True) -> Dict:
        """Query Wolfram Alpha with optional caching."""
        cache_key = self._get_cache_key(q)

        # Try cache first
        if use_cache:
            cached = self._load_from_cache(cache_key)
            if cached:
                return cached

        # Make API call
        url = "https://api.wolframalpha.com/v2/query"
        params = {
            "input": q,
            "appid": self.app_id,
            "output": "JSON",
            "format": "plaintext,mathml,image",
        }

        try:
            resp = self._requests.get(
                url, params=params, timeout=self.timeout_s)
            resp.raise_for_status()
            result = resp.json()

            # Cache successful results
            if result.get("queryresult", {}).get("success"):
                self._save_to_cache(cache_key, result)

            return result
        except Exception as e:
            raise RuntimeError(f"Wolfram Alpha query failed: {e}")

    @staticmethod
    def extract_primary_text(wa_json: Dict) -> str | None:
        """Extract primary plaintext result."""
        try:
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                if pod.get("primary"):
                    subs = pod.get("subpods", [])
                    for sp in subs:
                        pt = sp.get("plaintext")
                        if pt:
                            return pt
            for pod in pods:
                for sp in pod.get("subpods", []):
                    pt = sp.get("plaintext")
                    if pt:
                        return pt
        except Exception:
            return None
        return None

    @staticmethod
    def extract_structured_results(wa_json: Dict) -> Dict:
        """Extract structured results including LaTeX, MathML, and images."""
        result = {
            "plaintext": [],
            "latex": [],
            "mathml": [],
            "images": [],
            "assumptions": [],
            "sources": []
        }

        try:
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                # Extract assumptions
                if "assumptions" in pod:
                    result["assumptions"].extend(pod["assumptions"])

                # Extract sources
                if "sources" in pod:
                    result["sources"].extend(pod["sources"])

                # Extract subpod content
                for subpod in pod.get("subpods", []):
                    if "plaintext" in subpod:
                        result["plaintext"].append(subpod["plaintext"])
                    if "mathml" in subpod:
                        result["mathml"].append(subpod["mathml"])
                    if "latex" in subpod:
                        result["latex"].append(subpod["latex"])
                    if "img" in subpod:
                        result["images"].append(subpod["img"])

        except Exception:
            pass

        return result

    def needs_hitl_review(self, wa_json: Dict) -> bool:
        """Check if result needs human review (ambiguous, multiple interpretations)."""
        if not self.enable_hitl:
            return False

        try:
            # Check for ambiguous results
            pods = wa_json["queryresult"].get("pods", [])
            for pod in pods:
                # Multiple interpretations
                if len(pod.get("subpods", [])) > 3:
                    return True
                # Assumptions that might need review
                if pod.get("assumptions"):
                    return True
                # Error or warning states
                if pod.get("error") or pod.get("warning"):
                    return True
        except Exception:
            pass

        return False

    def get_hitl_prompt(self, query: str, wa_json: Dict) -> str:
        """Generate HITL review prompt for ambiguous results."""
        structured = self.extract_structured_results(wa_json)

        prompt = f"""Wolfram Alpha returned ambiguous results for query: "{query}"

Results:
- Plaintext: {structured['plaintext'][:3]}
- Assumptions: {structured['assumptions'][:2]}
- Sources: {structured['sources'][:2]}

Please review and select the most appropriate result, or provide clarification."""

        return prompt
